# -*- coding: utf-8 -*-
"""pandas_scrapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sCheeulMFljFKa1l3RLPV3WmaQ8QCHdy
"""

#Importar as Bibliotecas
import pandas as pd
import requests

#Criando um Header

#Pesquisar no navegador (My user agent) colar o caminho no Header
header = {'User-Agente': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 \
(KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'}

#Dados coletados do Investing.com (Ações do Brasil)
url = 'https://br.investing.com/equities/brazil'
request = requests.get(url, headers=header)

df = pd.read_html(request.text)
df

#Coletar as Informações em lista com o laço for 
for i , tabela in enumerate(df):
  print('-----------------------------')
  print(i)
  print(tabela)

#Data Frame
df = pd.DataFrame(df[0])

#Exibir Tabela
df

#Ajustando Data Frame (Formatando)
df['Último'] = df['Último'] / 100
df['Máxima'] = df['Máxima'] / 100
df['Mínima'] = df['Mínima'] / 100

##Exibir Tabela
df